"""
Purged K-Fold Cross-Validation with Sample Uniqueness Weighting.

Implements two key constructions from López de Prado, *Advances in Financial
Machine Learning* (2018):

  - **§4.5 Sample Uniqueness.**  When labels are generated by the Triple
    Barrier Method, each label spans a forward window
    ``[t, t + barrier_hit_time]``.  Many such windows overlap.  A naïvely-
    weighted training set therefore over-counts information from periods
    of dense overlap.  ``compute_average_uniqueness`` returns a per-sample
    weight equal to the average inverse-concurrency over each sample's
    span; passing these as ``sample_weight`` to a classifier removes the
    bias.

  - **§7.4 Purging and Embargo.**  Standard k-fold CV is invalid for
    overlapping-label time series: a label whose forward window straddles
    the train/test boundary leaks future information into training.
    ``PurgedKFold`` removes from each training fold any sample whose label
    span overlaps the test fold, then drops an additional
    ``embargo_pct * N`` rows immediately after the test fold to block
    short-horizon serial dependence.

Both helpers operate on the integer-bar form of ``barrier_hit_time``
emitted by ``tbm_labeler.apply_triple_barrier`` (the value is the
*number of forward bars* until the first barrier touch, in [1, time_limit]).

Usage
-----
>>> from purged_kfold import compute_average_uniqueness, PurgedKFold
>>> w = compute_average_uniqueness(df["barrier_hit_time"].values)
>>> cv = PurgedKFold(n_splits=5, barrier_hit_time=df["barrier_hit_time"].values,
...                  embargo_pct=0.01)
>>> for train_idx, test_idx in cv.split(X):
...     model.fit(X.iloc[train_idx], y.iloc[train_idx],
...               sample_weight=w[train_idx])
...     preds = model.predict_proba(X.iloc[test_idx])
"""

from __future__ import annotations

import numpy as np
from typing import Iterator, Tuple


def compute_concurrency(barrier_hit_time: np.ndarray) -> np.ndarray:
    """
    Number of *open* labels at every bar.

    A label at index ``i`` with forward horizon ``h_i = barrier_hit_time[i]``
    "occupies" bars ``i, i+1, ..., i+h_i``.  ``concurrency[t]`` is therefore
    the count of labels whose span contains ``t``.

    Implemented with a difference array so the cost is O(N).
    """
    n = len(barrier_hit_time)
    diff = np.zeros(n + 1, dtype=np.int64)
    h = np.asarray(barrier_hit_time, dtype=np.int64)
    # NaN/missing horizons are treated as 0 (label is its own bar only).
    h = np.where(np.isnan(h.astype(float)) if h.dtype.kind == "f" else False, 0, h)
    h = np.clip(h, 0, n - 1)

    starts = np.arange(n)
    ends = np.minimum(starts + h, n - 1)

    np.add.at(diff, starts, 1)
    np.add.at(diff, ends + 1, -1)
    concurrency = np.cumsum(diff)[:n]
    # Guard against zero in case a row had NaN horizon and no other label covers it.
    concurrency = np.maximum(concurrency, 1)
    return concurrency


def compute_average_uniqueness(barrier_hit_time: np.ndarray) -> np.ndarray:
    """
    Per-label average uniqueness ``u_i = mean_{t in span(i)} 1/concurrency[t]``.

    Returns a float array of shape ``(N,)`` suitable for use as
    ``sample_weight`` in any sklearn-compatible classifier.

    The weights are returned **unnormalized** (mean ≈ some value < 1).
    Most estimators handle this fine; if a particular estimator demands
    weights that sum to N, scale by ``len(w) / w.sum()`` at the call site.
    """
    n = len(barrier_hit_time)
    concurrency = compute_concurrency(barrier_hit_time).astype(np.float64)
    inv_conc = 1.0 / concurrency

    h = np.asarray(barrier_hit_time, dtype=np.int64)
    h = np.clip(h, 0, n - 1)

    # Cumulative sum of 1/concurrency so each label's span sum is O(1).
    cs = np.concatenate([[0.0], np.cumsum(inv_conc)])
    starts = np.arange(n)
    ends = np.minimum(starts + h, n - 1)
    span_sum = cs[ends + 1] - cs[starts]
    span_len = (ends - starts + 1).astype(np.float64)
    return span_sum / span_len


class PurgedKFold:
    """
    K-fold splitter that purges training samples whose label horizons
    overlap the test fold and applies a post-test embargo.

    Parameters
    ----------
    n_splits : int
        Number of folds.  Folds are contiguous time slices (no shuffling).
    barrier_hit_time : array-like of int
        Forward horizon (in bars) of each label, as emitted by
        ``tbm_labeler.apply_triple_barrier``.
    embargo_pct : float, default 0.01
        Fraction of total rows to drop from training immediately *after*
        each test fold (López de Prado's standard recommendation: 1%).
    """

    def __init__(
        self,
        n_splits: int,
        barrier_hit_time: np.ndarray,
        embargo_pct: float = 0.01,
    ):
        if n_splits < 2:
            raise ValueError("n_splits must be >= 2")
        self.n_splits = n_splits
        self.h = np.asarray(barrier_hit_time, dtype=np.int64)
        self.embargo_pct = float(embargo_pct)

    def split(self, X) -> Iterator[Tuple[np.ndarray, np.ndarray]]:
        n = len(X)
        if len(self.h) != n:
            raise ValueError(
                f"barrier_hit_time length ({len(self.h)}) does not match X length ({n})"
            )

        embargo_n = int(round(n * self.embargo_pct))
        fold_bounds = np.linspace(0, n, self.n_splits + 1, dtype=int)

        for k in range(self.n_splits):
            test_start, test_end = fold_bounds[k], fold_bounds[k + 1]
            test_idx = np.arange(test_start, test_end)

            # Purge: drop train samples whose forward span reaches into the
            # test fold (i.e. start < test_end AND start + h >= test_start).
            ends = np.arange(n) + self.h
            train_mask = np.ones(n, dtype=bool)
            train_mask[test_start:test_end] = False  # remove test rows themselves

            # Purge train rows whose span overlaps test region
            overlap = (np.arange(n) < test_end) & (ends >= test_start)
            train_mask &= ~overlap

            # Embargo: drop the embargo_n rows immediately after the test fold
            embargo_end = min(test_end + embargo_n, n)
            train_mask[test_end:embargo_end] = False

            train_idx = np.where(train_mask)[0]
            yield train_idx, test_idx

    def get_n_splits(self, X=None, y=None, groups=None) -> int:
        return self.n_splits


__all__ = [
    "compute_concurrency",
    "compute_average_uniqueness",
    "PurgedKFold",
]
