import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    brier_score_loss,
)
from sklearn.calibration import CalibratedClassifierCV
from sklearn.isotonic import IsotonicRegression
import json
import warnings
import argparse

from purged_kfold import PurgedKFold, compute_average_uniqueness

warnings.filterwarnings("ignore")

# ── Configuration ────────────────────────────────────────────────────────────
DATA_FILE = "fracdiff_alpha_dataset.csv"
TARGET_COL = "tbm_label"
# DROP_COLS — leakage-prevention list.  See README of train_model.py for the
# full justification of each entry; the critical ones for accuracy are:
#   target_return_4h  (regression label = close.shift(-4)−close — pure leak)
#   barrier_hit_time  (TBM resolution time, knows the future)
#   close_fd          (legacy name; collides with current close_fd_04)
DROP_COLS = ["timestamp", "target_return_4h", "barrier_hit_time", "close_fd"]
MODEL_SAVE_PATH = "tbm_xgboost_model_v2.json"
CALIBRATOR_SAVE_PATH = "tbm_xgboost_model_v2_calibrated.pkl"
THRESHOLD_SAVE_PATH = "tbm_xgboost_model_v2_threshold.json"
EMBARGO_FRACTION = 0.01  # 1% embargo gap to prevent label-leakage between train/val


def load_and_prepare_data():
    """
    Loads the fractionally differenced dataset and prepares it for time-series training.
    Returns (X, y, barrier_hit_time-or-None) so callers can decide whether to use
    sample-uniqueness weighting and purged k-fold CV.
    """
    print(f"Loading data from {DATA_FILE}...")
    df = pd.read_csv(DATA_FILE)

    # Capture barrier_hit_time BEFORE dropping it — it is needed downstream
    # for sample uniqueness weights and purged k-fold splits.
    bht = (
        df["barrier_hit_time"].astype(int).values
        if "barrier_hit_time" in df.columns
        else None
    )

    # If timestamp is a column (not index), it will be dropped
    cols_to_drop = [c for c in DROP_COLS if c in df.columns]
    print(f"Dropping non-feature columns: {cols_to_drop}")
    df = df.drop(columns=cols_to_drop)

    # Separate features (X) and target (y)
    X = df.drop(columns=[TARGET_COL])
    y = df[TARGET_COL].astype(int)

    print(f"Features used for training: {list(X.columns)}")

    # Verify 'close' is gone and 'close_fd_04' is present
    if "close" in X.columns:
        print("WARNING: 'close' column found in features. Dropping it.")
        X = X.drop(columns=["close"])
    if "close_fd_04" not in X.columns:
        print("WARNING: 'close_fd_04' column NOT found in features.")

    return X, y, bht


def time_series_split(X, y, train_size=0.70, val_size=0.15, embargo=EMBARGO_FRACTION):
    """
    Sequential split with an EMBARGO gap between train/val and val/test
    (López de Prado §7.4).  Without an embargo, labels generated by TBM near
    the train/val boundary can leak future information into the validation
    set because each label looks `timeHorizon` bars forward.
    """
    print(
        f"\nSplitting data sequentially ({int(train_size * 100)}/{int(val_size * 100)}/{int((1 - train_size - val_size) * 100)}) with {embargo * 100:.1f}% embargo..."
    )

    n = len(X)
    train_end = int(n * train_size)
    val_end = int(n * (train_size + val_size))
    embargo_n = int(n * embargo)

    X_train = X.iloc[: train_end - embargo_n]
    y_train = y.iloc[: train_end - embargo_n]

    X_val = X.iloc[train_end : val_end - embargo_n]
    y_val = y.iloc[train_end : val_end - embargo_n]

    X_test = X.iloc[val_end:]
    y_test = y.iloc[val_end:]

    print(f"Train samples: {len(X_train)}  (embargo={embargo_n} bars dropped at tail)")
    print(f"Validation samples: {len(X_val)}")
    print(f"Test samples: {len(X_test)}")

    return X_train, y_train, X_val, y_val, X_test, y_test


def find_best_threshold(y_true, probas, grid=None):
    """
    Pick the probability threshold that maximises F1 on the validation set.
    Replaces the hard-coded 0.65 cut-off in api.py — uncalibrated thresholds
    are model-specific and must be tuned per-model.
    """
    if grid is None:
        grid = np.arange(0.30, 0.81, 0.01)
    best_t, best_f1 = 0.5, -1.0
    for t in grid:
        pred = (probas >= t).astype(int)
        if pred.sum() == 0 or pred.sum() == len(pred):
            continue
        f = f1_score(y_true, pred)
        if f > best_f1:
            best_f1, best_t = f, t
    return float(best_t), float(best_f1)


def _make_xgb(scale_pos_weight: float, **overrides) -> xgb.XGBClassifier:
    """Factory so the purged-CV path and the simple-split path use identical hyper-params."""
    params = dict(
        objective="binary:logistic",
        eval_metric="logloss",
        scale_pos_weight=scale_pos_weight,
        n_estimators=500,
        learning_rate=0.05,
        max_depth=5,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        tree_method="hist",
        n_jobs=-1,
    )
    params.update(overrides)
    return xgb.XGBClassifier(**params)


def train_with_purged_kfold(
    X: pd.DataFrame,
    y: pd.Series,
    barrier_hit_time: np.ndarray,
    n_splits: int = 5,
    embargo_pct: float = EMBARGO_FRACTION,
):
    """
    Purged k-fold training (López de Prado §4.5 + §7.4).

    1. Computes per-sample average uniqueness weights from ``barrier_hit_time``.
    2. Generates out-of-fold (OOF) predictions using ``PurgedKFold`` so that
       calibration and threshold selection do not see leaked labels.
    3. Fits an isotonic calibrator on the OOF probabilities.
    4. Refits a final booster on ALL data (with the same uniqueness weights)
       and wraps it with the OOF-fit calibrator.

    Returns
    -------
    final_model : xgb.XGBClassifier
        The booster fit on all data (no early stopping — uses the median of
        the per-fold ``best_iteration`` values).
    calibrator : object exposing predict_proba (the isotonic regressor wrapped
        in a tiny adapter for parity with CalibratedClassifierCV).
    best_threshold, best_f1, brier : floats
        Diagnostics computed on the OOF predictions.
    oof_proba : np.ndarray
        Per-row OOF probability of class 1.  Useful for downstream meta-labeling.
    """
    print(f"\n=== Purged K-Fold training (k={n_splits}, embargo={embargo_pct:.1%}) ===")
    n = len(X)

    print("Computing sample uniqueness weights from barrier_hit_time...")
    weights = compute_average_uniqueness(barrier_hit_time)
    print(
        f"  weights: min={weights.min():.4f} mean={weights.mean():.4f} "
        f"max={weights.max():.4f}"
    )

    cv = PurgedKFold(
        n_splits=n_splits,
        barrier_hit_time=barrier_hit_time,
        embargo_pct=embargo_pct,
    )

    oof_proba = np.full(n, np.nan)
    best_iters = []
    for fold, (train_idx, test_idx) in enumerate(cv.split(X), start=1):
        # Use a small slice of train as a holdout for early stopping (last 10%).
        cut = int(len(train_idx) * 0.9)
        es_train = train_idx[:cut]
        es_val = train_idx[cut:]

        y_tr = y.iloc[es_train]
        spw = (y_tr == 0).sum() / max(1, (y_tr == 1).sum())
        m = _make_xgb(scale_pos_weight=float(spw), early_stopping_rounds=50)
        m.fit(
            X.iloc[es_train],
            y_tr,
            sample_weight=weights[es_train],
            eval_set=[(X.iloc[es_val], y.iloc[es_val])],
            verbose=False,
        )
        oof_proba[test_idx] = m.predict_proba(X.iloc[test_idx])[:, 1]
        best_iters.append(int(m.best_iteration or m.n_estimators))
        print(
            f"  fold {fold}: train={len(train_idx)}  test={len(test_idx)}  "
            f"best_iter={best_iters[-1]}"
        )

    valid = ~np.isnan(oof_proba)
    if not valid.any():
        raise RuntimeError("Purged k-fold produced no OOF predictions.")

    y_oof = y.values[valid]
    p_oof = oof_proba[valid]

    print("\nFitting isotonic calibrator on OOF predictions...")
    iso = IsotonicRegression(out_of_bounds="clip")
    iso.fit(p_oof, y_oof)

    p_oof_cal = iso.transform(p_oof)
    best_threshold, best_f1 = find_best_threshold(y_oof, p_oof_cal)
    brier = brier_score_loss(y_oof, p_oof_cal)
    print(
        f"OOF threshold (max F1): {best_threshold:.3f}  "
        f"(F1={best_f1:.4f}, Brier={brier:.4f})"
    )

    # Refit a final booster on ALL data, no early stopping. Use the median
    # best-iteration count from the folds as n_estimators.
    final_n = max(50, int(np.median(best_iters)))
    spw_full = (y == 0).sum() / max(1, (y == 1).sum())
    print(
        f"\nFitting final booster on full dataset (n_estimators={final_n}, "
        f"scale_pos_weight={spw_full:.3f}, weighted by sample uniqueness)..."
    )
    final_model = _make_xgb(scale_pos_weight=float(spw_full), n_estimators=final_n)
    # Remove early_stopping_rounds for the final fit
    final_model.set_params(early_stopping_rounds=None)
    final_model.fit(X, y, sample_weight=weights, verbose=False)

    # Wrap the isotonic regressor in a tiny object that mimics the
    # ``predict_proba`` interface of CalibratedClassifierCV so api.py and
    # the rest of the pipeline can treat the two artifacts interchangeably.
    class IsotonicCalibratorWrapper:
        """Mimics CalibratedClassifierCV(prefit).predict_proba shape."""

        def __init__(self, base_estimator, iso_regressor):
            self.base_estimator = base_estimator
            self.iso = iso_regressor

        def predict_proba(self, X):
            raw = self.base_estimator.predict_proba(X)[:, 1]
            cal = self.iso.transform(raw)
            cal = np.clip(cal, 0.0, 1.0)
            return np.column_stack([1.0 - cal, cal])

        def predict(self, X, threshold: float = 0.5):
            return (self.predict_proba(X)[:, 1] >= threshold).astype(int)

    calibrator = IsotonicCalibratorWrapper(final_model, iso)
    return final_model, calibrator, best_threshold, best_f1, brier, oof_proba


def main():
    parser = argparse.ArgumentParser(
        description="Train the v2 TBM XGBoost classifier with optional purged k-fold CV."
    )
    parser.add_argument(
        "--purged-kfold",
        action="store_true",
        help=(
            "Use purged k-fold CV with sample-uniqueness weights "
            "(López de Prado §4.5 + §7.4) instead of the simple 70/15/15 split. "
            "Recommended whenever barrier_hit_time is available in the dataset."
        ),
    )
    parser.add_argument(
        "--n-splits", type=int, default=5, help="Number of purged folds (default: 5)."
    )
    args = parser.parse_args()

    try:
        # 1. Load Data
        X, y, bht = load_and_prepare_data()

        if args.purged_kfold:
            if bht is None:
                raise ValueError(
                    "--purged-kfold requires the dataset to contain a "
                    "'barrier_hit_time' column. Re-run tbm_labeler.py."
                )
            (
                model,
                calibrator,
                best_threshold,
                best_f1,
                brier,
                oof_proba,
            ) = train_with_purged_kfold(
                X, y, bht, n_splits=args.n_splits, embargo_pct=EMBARGO_FRACTION
            )

            # Persist OOF probabilities — used by the meta-labeling layer
            # (train_meta_labeler.py) to learn a "act / abstain" decision.
            oof_path = "tbm_xgboost_model_v2_oof.csv"
            pd.DataFrame({"y": y.values, "oof_proba": oof_proba}).to_csv(
                oof_path, index=False
            )
            print(f"Saved OOF predictions to {oof_path}")

            # Save artifacts
            print(f"\nSaving raw model to {MODEL_SAVE_PATH}...")
            model.save_model(MODEL_SAVE_PATH)

            print(f"Saving calibrator to {CALIBRATOR_SAVE_PATH}...")
            import pickle

            with open(CALIBRATOR_SAVE_PATH, "wb") as f:
                pickle.dump(calibrator, f)

            print(f"Saving best threshold to {THRESHOLD_SAVE_PATH}...")
            with open(THRESHOLD_SAVE_PATH, "w") as f:
                json.dump(
                    {
                        "threshold": best_threshold,
                        "oof_f1": best_f1,
                        "oof_brier": brier,
                        "n_splits": args.n_splits,
                        "embargo_pct": EMBARGO_FRACTION,
                        "method": "purged_kfold_with_uniqueness_weights",
                        "note": "Use this threshold (not hardcoded 0.65) on calibrated probabilities in api.py",
                    },
                    f,
                    indent=2,
                )
            print("Done! Purged k-fold artifacts saved.")
            return

        # ── Legacy 70/15/15 split path (kept for back-compat) ───────────────
        # 2. Time-Series Split
        X_train, y_train, X_val, y_val, X_test, y_test = time_series_split(X, y)

        # 3. Handle Class Imbalance
        print("\nCalculating class imbalance ratio for scale_pos_weight...")
        count_0 = sum(y_train == 0)
        count_1 = sum(y_train == 1)

        if count_1 == 0:
            raise ValueError(
                "Training set has no positive (1) samples. Cannot train model. Try adjusting the threshold or obtaining more data."
            )

        scale_pos_weight = count_0 / count_1
        print(f"Count of class 0 (Loss/Time Expiry): {count_0}")
        print(f"Count of class 1 (Win): {count_1}")
        print(f"Calculated scale_pos_weight: {scale_pos_weight:.4f}")

        # 4. Model Initialization
        print("\nInitializing XGBoost Classifier...")
        model = _make_xgb(scale_pos_weight=scale_pos_weight, early_stopping_rounds=50)

        # 5. Model Training with Early Stopping
        print("Training model with early stopping (patience=50)...")
        model.fit(
            X_train,
            y_train,
            eval_set=[(X_train, y_train), (X_val, y_val)],
            verbose=False,
        )

        best_iteration = model.best_iteration
        print(f"Training completed. Best iteration: {best_iteration}")

        # ── 6a. PROBABILITY CALIBRATION ───────────────────────────────────
        print(
            "\nFitting isotonic calibrator on validation set (sklearn CalibratedClassifierCV)..."
        )
        calibrator = CalibratedClassifierCV(model, method="isotonic", cv="prefit")
        calibrator.fit(X_val, y_val)

        # ── 6b. THRESHOLD OPTIMISATION ────────────────────────────────────
        val_proba = calibrator.predict_proba(X_val)[:, 1]
        best_threshold, best_val_f1 = find_best_threshold(y_val, val_proba)
        brier = brier_score_loss(y_val, val_proba)
        print(
            f"Best threshold (max F1): {best_threshold:.3f}  (val F1={best_val_f1:.4f}, Brier={brier:.4f})"
        )

        # 7. Evaluation on Test Set with calibrated model + tuned threshold
        print("\nEvaluating CALIBRATED model on the unseen Test Set...")
        test_proba = calibrator.predict_proba(X_test)[:, 1]
        y_test_pred = (test_proba >= best_threshold).astype(int)

        print("\n--- Classification Report (calibrated, tuned-threshold) ---")
        print(classification_report(y_test, y_test_pred))

        print("--- Confusion Matrix ---")
        print(confusion_matrix(y_test, y_test_pred))

        # 8. Save Model + calibrator + threshold
        print(f"\nSaving raw model to {MODEL_SAVE_PATH}...")
        model.save_model(MODEL_SAVE_PATH)

        print(f"Saving calibrator to {CALIBRATOR_SAVE_PATH}...")
        import pickle

        with open(CALIBRATOR_SAVE_PATH, "wb") as f:
            pickle.dump(calibrator, f)

        print(f"Saving best threshold to {THRESHOLD_SAVE_PATH}...")
        with open(THRESHOLD_SAVE_PATH, "w") as f:
            json.dump(
                {
                    "threshold": best_threshold,
                    "val_f1": best_val_f1,
                    "val_brier": brier,
                    "method": "single_split",
                    "note": "Use this threshold (not hardcoded 0.65) on calibrated probabilities in api.py",
                },
                f,
                indent=2,
            )
        print("Done! All artifacts saved.")

    except FileNotFoundError:
        print(
            f"Error: Could not find '{DATA_FILE}'. Please ensure you run apply_fracdiff.py first."
        )
    except Exception as e:
        print(f"An unexpected error occurred: {e}")


if __name__ == "__main__":
    main()
